# -*- coding: utf-8 -*-
"""AI_PROJECT1_313561002.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eS7Ojp39J215ilGoOXTXEBEBFooy_e5c
"""

# Install required packages
!pip -q install google-api-python-client isodate nltk imbalanced-learn

import os
import re
import json
import math
import random
import warnings
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

import isodate
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, ConfusionMatrixDisplay, classification_report
)
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.inspection import permutation_importance

from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE

warnings.filterwarnings("ignore")

nltk.download("vader_lexicon")
sia = SentimentIntensityAnalyzer()

"""## Configuration"""

API_KEY = ""
TARGET_VIDEO_COUNT = 2000
PUBLISHED_AFTER = "2025-01-01T00:00:00Z"

# Use keyword-based search
KEYWORDS = [
    "vlog", "travel", "gaming", "food", "podcast", "news", "sports", "technology",
    "education", "comedy", "review", "highlights", "documentary",
    "tutorial", "interview", "live performance", "science", "finance"
]
SEARCH_ORDERS = ["viewCount", "relevance", "date"]

MAX_PAGES_PER_QUERY = 2
VIDEOS_PER_PAGE = 50

DATA_DIR = Path("/content/youtube_virality_project")
DATA_DIR.mkdir(parents=True, exist_ok=True)

RAW_JSON_PATH = DATA_DIR / "youtube_raw_videos.json"
CLEAN_CSV_PATH = DATA_DIR / "youtube_clean_dataset.csv"

random.seed(42)
np.random.seed(42)

print(DATA_DIR)

"""## Youtube API"""

# Build YouTube API client
youtube = build("youtube", "v3", developerKey=API_KEY)

def search_video_ids(youtube, keyword, order="relevance", max_pages=2, per_page=50, published_after=None):
    all_ids = []
    next_page_token = None

    for page_idx in range(max_pages):
        request_kwargs = dict(
            part="snippet",
            q=keyword,
            type="video",
            order=order,
            maxResults=per_page,
            pageToken=next_page_token,
        )
        if published_after:
            request_kwargs["publishedAfter"] = published_after

        request = youtube.search().list(**request_kwargs)
        response = request.execute()

        items = response.get("items", [])
        ids = [item["id"]["videoId"] for item in items if "videoId" in item.get("id", {})]
        all_ids.extend(ids)

        print(f"keyword={keyword!r}, order={order}, page={page_idx+1}, fetched_ids={len(ids)}, total_ids={len(all_ids)}")

        next_page_token = response.get("nextPageToken")
        if not next_page_token:
            break

    return all_ids


def fetch_video_details(youtube, video_ids, batch_size=50):
    all_items = []

    for i in range(0, len(video_ids), batch_size):
        batch_ids = video_ids[i:i+batch_size]
        request = youtube.videos().list(
            part="snippet,contentDetails,statistics",
            id=",".join(batch_ids),
            maxResults=batch_size,
        )
        response = request.execute()
        items = response.get("items", [])
        all_items.extend(items)
        print(f"Fetched details for batch {i//batch_size + 1}, items={len(items)}, total_items={len(all_items)}")

    return all_items

def parse_duration_seconds(iso_duration):
    try:
        return int(isodate.parse_duration(iso_duration).total_seconds())
    except Exception:
        return None

def clean_text(x):
    if x is None:
        return ""
    x = str(x)
    x = re.sub(r"\s+", " ", x)
    return x.strip()

all_video_ids = []

for keyword in KEYWORDS:
    for order in SEARCH_ORDERS:
        try:
            ids = search_video_ids(
                youtube,
                keyword=keyword,
                order=order,
                max_pages=MAX_PAGES_PER_QUERY,
                per_page=VIDEOS_PER_PAGE,
                published_after=PUBLISHED_AFTER,
            )
            all_video_ids.extend(ids)

            unique_so_far = len(set(all_video_ids))
            print(f"Unique video IDs so far: {unique_so_far}")

            if unique_so_far >= TARGET_VIDEO_COUNT:
                break
        except HttpError as e:
            print(f"Error while searching keyword={keyword}, order={order}: {e}")

    if len(set(all_video_ids)) >= TARGET_VIDEO_COUNT:
        break

# Deduplicate and trim to target size
unique_video_ids = list(dict.fromkeys(all_video_ids))[:TARGET_VIDEO_COUNT]
print(f"Total unique video IDs collected: {len(unique_video_ids)}")
all_videos = fetch_video_details(youtube, unique_video_ids)

unique = {}
for item in all_videos:
    vid = item.get("id")
    if vid and vid not in unique:
        unique[vid] = item

all_videos = list(unique.values())
print(f"Total unique videos with full metadata: {len(all_videos)}")

with open(RAW_JSON_PATH, "w", encoding="utf-8") as f:
    json.dump(all_videos, f, ensure_ascii=False, indent=2)

print(f"Saved raw dataset to: {RAW_JSON_PATH}")

"""## Convert JSON into DataFrame"""

rows = []
for item in all_videos:
    snippet = item.get("snippet", {})
    stats = item.get("statistics", {})
    content = item.get("contentDetails", {})

    rows.append({
        "video_id": item.get("id"),
        "title": snippet.get("title"),
        "description": snippet.get("description"),
        "publishedAt": snippet.get("publishedAt"),
        "channelTitle": snippet.get("channelTitle"),
        "categoryId": snippet.get("categoryId"),
        "defaultLanguage": snippet.get("defaultLanguage"),
        "defaultAudioLanguage": snippet.get("defaultAudioLanguage"),
        "tags": snippet.get("tags", []),
        "duration": content.get("duration"),
        "duration_seconds": parse_duration_seconds(content.get("duration")),
        "viewCount": pd.to_numeric(stats.get("viewCount"), errors="coerce"),
        "likeCount": pd.to_numeric(stats.get("likeCount"), errors="coerce"),
        "commentCount": pd.to_numeric(stats.get("commentCount"), errors="coerce"),
    })

df_raw = pd.DataFrame(rows)
print(df_raw.shape)
df_raw.head()

"""## Feature Engineering"""

df = df_raw.copy()
df["title"] = df["title"].apply(clean_text)
df["description"] = df["description"].apply(clean_text)
df["channelTitle"] = df["channelTitle"].apply(clean_text)
df["defaultLanguage"] = df["defaultLanguage"].fillna("")

# only en videos
# df = df[df["defaultLanguage"] == "en"].copy()
df["defaultLanguage"] = df["defaultLanguage"].fillna("")
df["defaultAudioLanguage"] = df["defaultAudioLanguage"].fillna("")

df = df[
    (df["defaultLanguage"] == "en") &
    (df["defaultAudioLanguage"].str.contains("en"))
].copy()

df = df[df["duration_seconds"] >= 61].copy()

# basic engineered features
df["title_length"] = df["title"].apply(len)
df["num_tags"] = df["tags"].apply(lambda x: len(x) if isinstance(x, list) else 0)

published_dt = pd.to_datetime(df["publishedAt"], errors="coerce", utc=True)
df["publish_hour"] = published_dt.dt.hour
df["publish_day"] = published_dt.dt.day_name()

df["like_ratio"] = np.where(df["viewCount"] > 0, df["likeCount"] / df["viewCount"], 0.0)
df["comment_ratio"] = np.where(df["viewCount"] > 0, df["commentCount"] / df["viewCount"], 0.0)

df["sentiment_score"] = df["title"].apply(lambda x: sia.polarity_scores(x)["compound"])
df["description_length"] = df["description"].apply(len)

df["log_viewCount"] = np.log1p(df["viewCount"])
df["log_likeCount"] = np.log1p(df["likeCount"])
df["log_commentCount"] = np.log1p(df["commentCount"])

df = df.dropna(subset=["viewCount", "categoryId", "duration_seconds", "publish_hour", "publish_day"]).copy()

# category_thresholds = df.groupby("categoryId")["viewCount"].quantile(0.75).to_dict()
# df["category_viral_threshold"] = df["categoryId"].map(category_thresholds)
# df["viral"] = (df["viewCount"] >= df["category_viral_threshold"]).astype(int)

# print("Dataset size after filtering:", len(df))
# print(df["viral"].value_counts())
# print(df[["defaultLanguage", "duration_seconds"]].head())

# print(df.isna().sum())
# print()
# print(df.describe(include="all").T.head(20))

print("Before filtering:", len(df_raw))
print("After English filter:", len(df_raw[df_raw["defaultLanguage"].fillna("") == "en"]))
print("After Shorts filter:", len(df))

# Save cleaned dataset
df.to_csv(CLEAN_CSV_PATH, index=False, encoding="utf-8")

plt.figure(figsize=(8, 5))
df["viewCount"].dropna().hist(bins=30)
plt.title("Distribution of View Count")
plt.xlabel("viewCount")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8, 5))
df["categoryId"].astype(str).value_counts().head(15).plot(kind="bar")
plt.title("Top Video Categories")
plt.xlabel("categoryId")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8, 5))
df.groupby("publish_day")["viral"].mean().reindex(
    ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]
).plot(kind="bar")
plt.title("Viral Rate by Publish Day")
plt.xlabel("Publish Day")
plt.ylabel("Mean viral label")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8, 5))
df.groupby("publish_hour")["viral"].mean().plot()
plt.title("Viral Rate by Publish Hour")
plt.xlabel("Publish Hour")
plt.ylabel("Mean viral label")
plt.grid(True, alpha=0.3)
plt.show()

feature_cols_with_sentiment = [
    "categoryId",
    "duration_seconds",
    "title_length",
    "description_length",
    "num_tags",
    "publish_hour",
    "publish_day",
    "like_ratio",
    "comment_ratio",
    "sentiment_score",
]

feature_cols_without_sentiment = [
    "categoryId",
    "duration_seconds",
    "title_length",
    "description_length",
    "num_tags",
    "publish_hour",
    "publish_day",
    "like_ratio",
    "comment_ratio",
]

target_col = "viral"

X_with_sentiment = df[feature_cols_with_sentiment].copy()
X_without_sentiment = df[feature_cols_without_sentiment].copy()
y = df[target_col].copy()

categorical_features = ["categoryId", "publish_day"]
numeric_features_with_sentiment = [c for c in feature_cols_with_sentiment if c not in categorical_features]
numeric_features_without_sentiment = [c for c in feature_cols_without_sentiment if c not in categorical_features]

print(X_with_sentiment.shape, y.shape)
print(y.value_counts())

def make_preprocessor(numeric_features, categorical_features, use_pca=False, n_components=5):
    numeric_steps = [
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
    ]
    if use_pca:
        numeric_steps.append(("pca", PCA(n_components=n_components)))

    numeric_transformer = Pipeline(steps=numeric_steps)

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore")),
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, numeric_features),
            ("cat", categorical_transformer, categorical_features),
        ]
    )
    return preprocessor

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scoring = {
    "accuracy": "accuracy",
    "precision": "precision",
    "recall": "recall",
    "f1": "f1",
}

def evaluate_model(X, y, model, numeric_features, categorical_features, use_pca=False, smote=False, label="model"):
    preprocessor = make_preprocessor(
        numeric_features=numeric_features,
        categorical_features=categorical_features,
        use_pca=use_pca,
        n_components=min(5, len(numeric_features)) if len(numeric_features) > 1 else 1
    )

    if smote:
        pipeline = ImbPipeline(steps=[
            ("preprocessor", preprocessor),
            ("smote", SMOTE(random_state=42)),
            ("model", model),
        ])
    else:
        pipeline = Pipeline(steps=[
            ("preprocessor", preprocessor),
            ("model", model),
        ])

    scores = cross_validate(
        pipeline, X, y, cv=cv, scoring=scoring, return_train_score=False
    )

    result = {
        "label": label,
        "accuracy_mean": scores["test_accuracy"].mean(),
        "precision_mean": scores["test_precision"].mean(),
        "recall_mean": scores["test_recall"].mean(),
        "f1_mean": scores["test_f1"].mean(),
        "accuracy_std": scores["test_accuracy"].std(),
        "precision_std": scores["test_precision"].std(),
        "recall_std": scores["test_recall"].std(),
        "f1_std": scores["test_f1"].std(),
    }
    return result, pipeline

dt_model = DecisionTreeClassifier(max_depth=5, random_state=42)
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=8,
    min_samples_split=5,
    random_state=42,
    n_jobs=-1
)

"""## Results"""

results = []

res_dt, dt_pipe = evaluate_model(
    X_with_sentiment, y, dt_model,
    numeric_features_with_sentiment, categorical_features,
    use_pca=False, smote=False, label="DecisionTree"
)
results.append(res_dt)

res_rf, rf_pipe = evaluate_model(
    X_with_sentiment, y, rf_model,
    numeric_features_with_sentiment, categorical_features,
    use_pca=False, smote=False, label="RandomForest"
)
results.append(res_rf)

results_df = pd.DataFrame(results).sort_values("f1_mean", ascending=False)
results_df

"""## Experiment A — With vs without sentiment


"""

experiment_sentiment = []

for model_name, model in [
    ("DecisionTree", dt_model),
    ("RandomForest", rf_model)
]:
    res_no_sent, _ = evaluate_model(
        X_without_sentiment, y, model,
        numeric_features_without_sentiment, categorical_features,
        use_pca=False, smote=False, label=f"{model_name}_without_sentiment"
    )
    experiment_sentiment.append(res_no_sent)

    res_with_sent, _ = evaluate_model(
        X_with_sentiment, y, model,
        numeric_features_with_sentiment, categorical_features,
        use_pca=False, smote=False, label=f"{model_name}_with_sentiment"
    )
    experiment_sentiment.append(res_with_sent)

sentiment_df = pd.DataFrame(experiment_sentiment).sort_values("f1_mean", ascending=False)
sentiment_df

"""## Experiment B — Effect of dataset size"""

def sample_dataframe_by_fraction(df, fraction, target_col="viral", random_state=42):
    sampled_parts = []
    for cls, grp in df.groupby(target_col):
        sampled_parts.append(grp.sample(frac=fraction, random_state=random_state))
    return pd.concat(sampled_parts).sample(frac=1.0, random_state=random_state).reset_index(drop=True)

size_results = []

for frac in [0.4, 0.7, 1.0]:
    df_sub = sample_dataframe_by_fraction(df, frac, target_col="viral")
    X_sub = df_sub[feature_cols_with_sentiment].copy()
    y_sub = df_sub[target_col].copy()

    for model_name, model in [
        ("DecisionTree", dt_model),
        ("RandomForest", rf_model)
    ]:
        res, _ = evaluate_model(
            X_sub, y_sub, model,
            numeric_features_with_sentiment, categorical_features,
            use_pca=False, smote=False,
            label=f"{model_name}_fraction_{frac}"
        )
        res["fraction"] = frac
        size_results.append(res)

size_results_df = pd.DataFrame(size_results).sort_values(["fraction", "f1_mean"], ascending=[True, False])
size_results_df

"""## Experiment C — Class imbalance handling with SMOTE

"""

smote_results = []

for model_name, model in [
    ("DecisionTree", dt_model),
    ("RandomForest", rf_model)
]:
    res_no_smote, _ = evaluate_model(
        X_with_sentiment, y, model,
        numeric_features_with_sentiment, categorical_features,
        use_pca=False, smote=False,
        label=f"{model_name}_no_SMOTE"
    )
    smote_results.append(res_no_smote)

    res_smote, _ = evaluate_model(
        X_with_sentiment, y, model,
        numeric_features_with_sentiment, categorical_features,
        use_pca=False, smote=True,
        label=f"{model_name}_with_SMOTE"
    )
    smote_results.append(res_smote)

smote_df = pd.DataFrame(smote_results).sort_values("f1_mean", ascending=False)
smote_df

"""## Experiment D — With vs without PCA

"""

pca_results = []

for model_name, model in [
    ("DecisionTree", dt_model),
    ("RandomForest", rf_model)
]:
    res_no_pca, _ = evaluate_model(
        X_with_sentiment, y, model,
        numeric_features_with_sentiment, categorical_features,
        use_pca=False, smote=False,
        label=f"{model_name}_no_PCA"
    )
    pca_results.append(res_no_pca)

    res_pca, _ = evaluate_model(
        X_with_sentiment, y, model,
        numeric_features_with_sentiment, categorical_features,
        use_pca=True, smote=False,
        label=f"{model_name}_with_PCA"
    )
    pca_results.append(res_pca)

pca_df = pd.DataFrame(pca_results).sort_values("f1_mean", ascending=False)
pca_df